Add ECR description automation and refactor template generation (#112)
Signed-off-by: Hanxi Zhang <hanxizh@amazon.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -170,7 +170,7 @@ jobs:
           provenance: false
           load: false
 
-  update-ecr-description:
+  update-dockerhub-ecr-description-file:
     if: |
       (github.event_name == 'push' &&
       github.ref == 'refs/heads/mainline' &&
@@ -179,27 +179,50 @@ jobs:
       - generate-jobs
       - test
       - build_and_push
-    name: Update ECR Description
+    name: Update Description File
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
+      - name: Update Description File
+        run: |
+            echo '${{ needs.generate-jobs.outputs.test_strategy }}' > bashbrew_output.json   
+            python generate-repo-description.py bashbrew_output.json description-template.md
+
+            for file in dockerhub-description.md ecr-about.md ecr-usage.md; do
+              if [ ! -f "$file" ]; then
+                echo "Error: $file was not created!"
+                exit 1
+              fi
+              echo "$file exists"
+            done
+
+      - name: Upload description files
+        uses: actions/upload-artifact@v4
+        with:
+          name: description-files
+          path: |
+            dockerhub-description.md
+            ecr-about.md
+            ecr-usage.md
+
+  update-descriptions:
+    if: |
+      (github.event_name == 'push' &&
+      github.ref == 'refs/heads/mainline' &&
+      fromJson(needs.generate-jobs.outputs.publish_strategy).matrix.include[0])
+    needs:
+      - update-dockerhub-ecr-description-file
+      - generate-jobs
+      - test
+      - build_and_push
+    name: Update Descriptions
     permissions:
       id-token: write
       contents: read
-    uses: ./.github/workflows/update-ecr-description.yml
-    secrets:
-      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-      ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}
-  
-  update-dockerhub-description:
-    if: |
-      (github.event_name == 'push' &&
-      github.ref == 'refs/heads/mainline' &&
-      fromJson(needs.generate-jobs.outputs.publish_strategy).matrix.include[0])
-    needs:
-      - generate-jobs
-      - test
-      - build_and_push
-    name: Update DockerHub Description
-    uses: ./.github/workflows/update-dockerhub-docs.yml
+    uses: ./.github/workflows/update-descriptions.yml
     secrets:
       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
       DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
+      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+      ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}
